### ISSUE TITLE
name of the resourceGroup can't be used

### ISSUE THREAD

**Issue by pherbel** [nianton/azure-naming#3]
This way I can't use the name of the resource group.
Maybe this module can be subscription scope?
```
resource rg 'Microsoft.Resources/resourceGroups@2021-04-01' = {
  name: 'rg-${applicationName}-${environment}'
  location: location
  tags: defaultTags
}

module naming 'modules/naming.module.bicep' = {
  scope: resourceGroup(rg.name)
  name: 'NamingDeployment'  
  params: {
    suffix: [
      applicationName
      environment
    ]
    uniqueLength: 6
    uniqueSeed: rg.id
  }
}
```

**Comment by nianton** [comment]
Hello Peter, thanks for the feedback!

You are right, it cannot be used for naming a resource group, but if the naming module was a subscription scoped one, it would still require an additional level of module nesting to consume its output for naming a resource (see bicep behavior/error below), making it a bit more difficult to work with. Lastly, if module has a subscription targetScope, requires that the hosting template to be at least at the same scope level (subscription), which requires much wider scoped rights from the initiator of the deployment.

Bicep error when trying to use the output of module on the same level for the `name` property of a resource (in this case of the resource group): 
`This expression is being used in an assignment to the "name" property of the "Microsoft.Resources/resourceGroups" type, which requires a value that can be calculated at the start of the deployment. Properties of naming which can be calculated at the start include "name".bicep(BCP120)`

So, for now at least, I deem that naming the necessary resource groups "by hand" is a compromise to improve the overall usability. Please find the gist targeting subscription, if needed (the only changes are the default values for `uniqueSeed` and `location`: https://gist.github.com/nianton/f7b493f9e8f9b618d82b48c09a15dab7
