### ISSUE TITLE
storage table names don't allow dashes

### ISSUE THREAD

**Issue by engenb** [nianton/azure-naming#4]
the azure storage table naming convention is configured to use dashes/separators, but azure tables do not allow dashes ([reference](https://learn.microsoft.com/en-us/rest/api/storageservices/understanding-the-table-service-data-model#table-names))

is the config wrong here or am I misunderstanding something?

happy to submit a PR if that's helpful.

````json
{
    "name": "storage_table",
    "length": {
      "min": 3,
      "max": 63
    },
    "regex": "^(?=.{3,63}$)(?!.*--)[a-z0-9][a-z0-9-]+[a-z0-9]$",
    "scope": "parent",
    "slug": "stt",
    "dashes": true,
    "description": "Storage Table"
  }

**Comment by nianton** [comment]
Great catch! Thank you for the feedback @engenb! The fix was just committed.
